const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: './images/p1.jpg',
      price: 129,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: './images/p2.jpg',
      price: 319,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 13,
      description: 'High quality product',
    },
    {
      _id: '3',
      name: 'Malabar check Shirt',
      category: 'Shirts',
      image: './images/p3.jpg',
      price: 229,
      brand: 'Malabar',
      rating: 4.2,
      numReviews: 7,
      description: 'High quality product',
    },
    {
      _id: '4',
      name: 'CottonKing Formal Pant',
      category: 'Pants',
      image: './images/p4.jpg',
      price: 129,
      brand: 'CottonKing',
      rating: 2.5,
      numReviews: 19,
      description: 'High quality product',
    },
    {
      _id: '5',
      name: 'HRX Pant',
      category: 'Pants',
      image: './images/p5.jpg',
      price: 120,
      brand: 'HRX',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '6',
      name: 'Puma Pant',
      category: 'Pants',
      image: './images/p6.jpg',
      price: 420,
      brand: 'Puma',
      rating: 5.0,
      numReviews: 22,
      description: 'High quality product',
    },
  ],
};

export default data;
